# https://taskfile.dev
version: '3'

silent: true

vars:
  GO_MODULE: github.com/FischukSergey/chat-service # FIXME сделал
  GO_FILES:
    sh: find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./internal/store/*" -not -path "*.gen.go" | tr "\n" " "

  GOLANGCI_LINT_VERSION: v1.61.0
  GOLANGCI_LINT_CACHE:
    sh: echo "$HOME/Library/Caches/golangci-lint" # сделал отдельную директорию для кэша

  DEV_TOOLS: |
    github.com/daixiang0/gci@v0.10.1
    mvdan.cc/gofumpt@v0.4.0
    github.com/kazhuravlev/options-gen/cmd/options-gen@v0.33.2
    entgo.io/ent/cmd/ent@v0.14.4

  ENT_SCHEMA: ./internal/store/schema

  DOCKER_COMPOSE_PATHS: >-
    -f ./deploy/local/docker-compose.yml
    -f ./deploy/local/docker-compose.sentry.yml

  DOCKER_COMPOSE_CMD: "docker compose"

  TYPES: >-
    ChatID
    MessageID
    ProblemID
    UserID
  TYPES_PKG: types
  TYPES_DST: ./internal/types/types.gen.go

tasks:
  default:
    cmds:
      # Последовательно выполняем таски tidy, fmt, lint, tests и build
      - task: tidy
      - task: fmt
      - task: lint
      - task: tests
      - task: build

  tidy:
    - echo "- Tidy"
    - go mod tidy
    - task: vendor

  vendor:
    - echo "- Vendor"
    - go mod vendor

  fmt:
    - echo "- Format"
    - gofumpt -w {{.GO_FILES}}
    - gci write --section Standard --section Default --section "Prefix({{.GO_MODULE}})" {{.GO_FILES}}

  lint:
    cmds:
      - echo "- Lint"
      - mkdir -p {{.GOLANGCI_LINT_CACHE}}
      - task: lint:cmd
        vars: {CLI_ARGS: "run -v --fix --timeout=5m ./..."}

  lint:cmd:
    cmds:
      - |
        docker run --rm \
          -v "$(pwd):/app" -w /app \
          -v "{{.GOLANGCI_LINT_CACHE}}:/root/.cache" \
          golangci/golangci-lint:{{.GOLANGCI_LINT_VERSION}} \
          golangci-lint {{.CLI_ARGS}}

  tests:
    cmds:
      - echo "- Tests"
      - go test -race -ldflags=-extldflags=-Wl,-ld_classic ./...
  tests:integration:
    env:
      TEST_LOG_LEVEL: info
      TEST_KEYCLOAK_REALM: Bank
      TEST_KEYCLOAK_CLIENT_ID: integration-testing
      TEST_KEYCLOAK_CLIENT_SECRET: 690PX438Tu1u2U3c2e9qJQmmjhfNeOSE
      TEST_KEYCLOAK_TEST_USER: integration-testing                  # FIXME: Поменяйте на ваше значение!
      TEST_KEYCLOAK_TEST_PASSWORD: integration-testing              # FIXME: Поменяйте на ваше значение!
    cmds:
      - echo "- Integration tests"
      - go test -tags integration -count 1 -race ./...

  build:
    cmds:
      - echo "- Build"
      - go build ./cmd/chat-service

  dev-tools:install:
    cmds:
      - echo "- Install dev tools"
      - for tool in {{.DEV_TOOLS}}; do go install $$tool; done

  generate:
    - echo "Run go generate..."
    - go generate ./...
    - task: gen:types
    - task: ent:gen

  gen:types:
    cmds:
      - echo "Generate types..."
      - |
        TYPES_ARG=$(echo "{{.TYPES}}" | tr ' ' ',' | sed 's/,$//')
        go run ./cmd/gen-types/main.go {{.TYPES_PKG}} "$TYPES_ARG" {{.TYPES_DST}}

# работаем с docker compose
  deps:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} {{.DOCKER_COMPOSE_PATHS}} up -d"

  deps:cmd:
    cmds:
      # Дать произвольную команду "docker compose"-у.
      # `task deps:cmd -- rm -fsv` == `docker compose rm -fsv`
      - "{{.DOCKER_COMPOSE_CMD}} {{.CLI_ARGS}}"

  deps:status:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} {{.DOCKER_COMPOSE_PATHS}} ps"

  deps:logs:
    cmds:
      # Показывает логи всех сервисов или одного, например,
      # `task deps:logs`
      # `task deps:logs -- postgres`
      - "{{.DOCKER_COMPOSE_CMD}} -f {{.DOCKER_COMPOSE_PATHS}} logs {{.CLI_ARGS}}"

  deps:stop:
    cmds:
      # Останавливает запущенные сервисы.
      - "{{.DOCKER_COMPOSE_CMD}} {{.DOCKER_COMPOSE_PATHS}} stop"

  deps:reset-psql:
    cmds:
      - task: deps:reset
        vars:
          SERVICE: postgres

  deps:reset:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} rm -fsv {{.SERVICE}}"
      - "{{.DOCKER_COMPOSE_CMD}} up -d {{.SERVICE}}"

  deps:sentry:
  desc: "Запускает Sentry для мониторинга ошибок"
  cmds:
    - COMPOSE_PROFILES=sentry {{.DOCKER_COMPOSE_CMD}} {{.DOCKER_COMPOSE_PATHS}} up -d

  deps:sentry:init:
  desc: "Инициализирует Sentry"
  cmds:
    - COMPOSE_PROFILES=sentry {{.DOCKER_COMPOSE_CMD}} {{.DOCKER_COMPOSE_PATHS}} exec sentry sentry upgrade

# генерация ent схемы
  ent:gen:
    cmds:
      - echo "Generate ent schema..."
      - GOFLAGS="-mod=mod" go run entgo.io/ent/cmd/ent generate {{.ENT_SCHEMA}}
      - task: tidy

  ent:new:
    desc: "Generate multiple ent schemas at once"
    cmds:
      - echo "Generating ent schemas for Chat, Message, and Problem..."
      - GOFLAGS="-mod=mod" go run entgo.io/ent/cmd/ent new --target {{.ENT_SCHEMA}} Chat Message Problem
      - task: tidy
