services:
  redis:
    image: redis:alpine
    profiles:
      - sentry
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "1234567890"

  sentry:
    image: sentry:latest
    platform: linux/amd64
    profiles:
      - sentry
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      SENTRY_SECRET_KEY: "1234567890"
      SENTRY_REDIS_HOST: "redis"
      SENTRY_REDIS_PORT: "6379"
      SENTRY_REDIS_DB: "0"
      SENTRY_REDIS_PASSWORD: "1234567890"
      # пользователь и пароль для входа в Sentry
      SENTRY_ADMIN_EMAIL: "sergey.fischuk67@gmail.com"
      SENTRY_ADMIN_PASSWORD: "1234567890"
    volumes:
      - sentry-data:/sentry
    depends_on:
      - redis
      - postgres

  sentry_cron:
    image: sentry:latest
    platform: linux/amd64
    profiles:
      - sentry
    command: "sentry run cron"
    environment:
      SENTRY_SECRET_KEY: "1234567890"
      SENTRY_REDIS_HOST: "redis"
      SENTRY_REDIS_PORT: "6379"
      SENTRY_REDIS_DB: "0"
      SENTRY_REDIS_PASSWORD: "1234567890"
    depends_on:
      - redis
      - postgres

  sentry_worker:
    image: sentry:latest
    platform: linux/amd64
    profiles:
      - sentry
    command: "sentry run worker"
    environment:
      SENTRY_SECRET_KEY: "1234567890"
      SENTRY_REDIS_HOST: "redis"
      SENTRY_REDIS_PORT: "6379"
      SENTRY_REDIS_DB: "0"
      SENTRY_REDIS_PASSWORD: "1234567890"
    depends_on:
      - redis
      - postgres

volumes:
  sentry-data:
