// Package clientv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package clientv1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/FischukSergey/chat-service/internal/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	// Code contains HTTP error codes and specific business logic error codes (the last must be >= 1000).
	Code    ErrorCode `json:"code"`
	Details *string   `json:"details,omitempty"`
	Message string    `json:"message"`
}

// ErrorCode contains HTTP error codes and specific business logic error codes (the last must be >= 1000).
type ErrorCode = int

// GetHistoryRequest defines model for GetHistoryRequest.
type GetHistoryRequest struct {
	// Cursor Курсор для пагинации
	Cursor   *string `json:"cursor"`
	PageSize *int    `json:"pageSize"`
}

// GetHistoryResponse defines model for GetHistoryResponse.
type GetHistoryResponse struct {
	Data  *MessagesPage `json:"data,omitempty"`
	Error *Error        `json:"error,omitempty"`
}

// Message defines model for Message.
type Message struct {
	AuthorId   *types.UserID   `json:"authorId,omitempty"`
	Body       string          `json:"body"`
	CreatedAt  time.Time       `json:"createdAt"`
	Id         types.MessageID `json:"id"`
	IsBlocked  bool            `json:"isBlocked"`
	IsReceived bool            `json:"isReceived"`
	IsService  bool            `json:"isService"`
}

// MessagesPage defines model for MessagesPage.
type MessagesPage struct {
	Messages []Message `json:"messages"`

	// NextCursor Курсор для следующей страницы.
	// Если нет следующей страницы, то не возвращается.
	// Если нет курсора, то возвращается пустая строка.
	NextCursor *string `json:"nextCursor"`

	// PrevCursor Курсор для предыдущей страницы.
	// Если нет предыдущей страницы, то не возвращается.
	// Если нет курсора, то возвращается пустая строка.
	PrevCursor *string `json:"prevCursor"`
}

// XRequestIDHeader defines model for XRequestIDHeader.
type XRequestIDHeader = types.RequestID

// PostGetHistoryParams defines parameters for PostGetHistory.
type PostGetHistoryParams struct {
	// XRequestID Unique request identifier
	XRequestID XRequestIDHeader `json:"X-Request-ID"`
}

// PostGetHistoryJSONRequestBody defines body for PostGetHistory for application/json ContentType.
type PostGetHistoryJSONRequestBody = GetHistoryRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /getHistory)
	PostGetHistory(ctx echo.Context, params PostGetHistoryParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostGetHistory converts echo context to params.
func (w *ServerInterfaceWrapper) PostGetHistory(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostGetHistoryParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID XRequestIDHeader
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Request-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Request-ID: %s", err))
		}

		params.XRequestID = XRequestID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Request-ID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostGetHistory(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/getHistory", wrapper.PostGetHistory)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RX3W4Txxd/ldH8/xettFk7pRdopV5AKJCqqBEJKhLOxXj3xB7Y3VlmZiPSaKV8IBBK",
	"C1Kl3vSmr+AGrJiPOK9w5o2qM2vHNjYlIHHRK2dnzufv/M6Zk10eq6xQOeTW8GiXF0KLDCxo/3X3Njws",
	"wdjVazdBJKDpLAETa1lYqXIe8Tu5fFgC07UckwnkVm5J0DzgkgS6tWLAc5EBj/jdpZHNpdVrPOCkKDUk",
	"PLK6hICbuAuZID9bSmfC8oiXpUx4wO1OQfrGapl3eMAfLXXU0uiQfkx4Huz07ZLMCqVtnZvt8oh3pO2W",
	"7TBWWeO6NHG3fLAOugM7jbgr7JIBvS1jaMjcgs5F2vC2eVVV1Tg6D833WiuPR6FVAdpK8MexSoB+/69h",
	"i0f8f40JvI2RdsOrrpBgFfAErJCp153NsAp4BsaIDiy4q6aRu3cuGNT+N6uAT5zM1SxWuRUyN+zmxsYa",
	"AxJkpGeYyBNmCojlloxZuzQyB2NYqjoynpH7ynaBpcJYlpXGsjawVtlsXoLv2HKz2fw65AHPZC6zMuPR",
	"t83mefEI1A5oyu0G2JvSWKV3RmVbgGWpjVrAOfzTHbo9t49Dt8fwFb51LxieYQ9f4gBPseee4AAHRLky",
	"TUU7hTG55gAuRAfW5S8jjLZEmVoeLTcDnolHdfTLFP15LssftHmeWXV+pNr3Ibbv52oKlRuYTzYRVnyM",
	"OLfqMps1qnUVcBhz8KNs456+tyZ8mnUuSttVejX5vL67Y0B/oaYLeFslOwubI9YgLCRX7EzQibCwZGUG",
	"fEG55WcmOMLti+UozdVUxQ8gmUq0rVQKIvdhm9sQg9z+8P16bXvR9XuTwmfsMZ1GcMbHdDzTxjcXMHuG",
	"kXO0Go0l/7e0kJkLEpxPmkhoLXboO4dHduUTBoLbx7fYx1fu0D13z7CPr5nbdwduD3t4igP3xB2FrRz/",
	"8HIDhqfYdwcX0QqYO8ChV2B4jEM8wWO6d8+wRzbcvnuxwDK+mcSIvbGRD+gzPHOH5Bh7PhUfwRDfYC9s",
	"5RcabBq2Vz5pfLo9n/eRz/3CeF1I7z+A2OL31CzgPG0BEJda2p11Ym3N7jYIDfpKSXNg/HV9PGd++HmD",
	"j3YH35r+djJ4utYW9XyW+Zaar9eVtdUpUvfdHh7jwO1jj7mn2CNU8DhkrRx/p2uGJ9jzZRm6fXfE/I+v",
	"jEfnmOy452PQ3hF+OMRXOMR3bO2n9Y1wYmjo5QngI4YDL/uceuSxr8g78s12W/7lavGI7YZhWFUkSUXc",
	"bdXP0+QmbOWtHP9yeyNbT2uGYD9ioxSHvm6HeIanOKTs+p5dJwz/xh6eUKLuCF+zO7d/jBjBFjUaqYpF",
	"2lXGRpebl5uT4IkOB0SmY0LtDPu0FbjHOCBO1BsCc4f04QE7raE6IM9uHwfuAPv41v1aR/KbB+klDsl1",
	"TSgrLbGJXxX5A7ZeFvQWsJWusGwllZBbyokHfBu0qcu4vUyNqQrIRSF5xC+FzfASD/zj4TnU6JyvCX6U",
	"qnonmiXDDbCMnhPWrSVp1aKRK+ieHnC+poydLBzewWSlv7d4/k5EGnMrf7VZ9wYYe3X0FtMCCbmPThRF",
	"KmPvvXHfUIi7Uzv8v836+QWwmm1DalR/UK9MHqNvms0vEsBoK/MRzAI+fuFYKo0N/f8BUyPAIzrd/Pc2",
	"CS9668d4z5q7BtuQqiIjhtRSPOClTkdzYI7QDaLNZvVPAAAA//9vowTypw0AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
