// Code generated by ent, DO NOT EDIT.

package store

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
)

// Database is the client that holds all ent builders.
type Database struct {
	client *Client
}

// NewDatabase creates a new database based on Client.
func NewDatabase(client *Client) *Database {
	return &Database{client: client}
}

// RunInTx runs the given function f within a transaction.
// Inspired by https://entgo.io/docs/transactions/#best-practices.
// If there is already a transaction in the context, then the method uses it.
func (db *Database) RunInTx(ctx context.Context, f func(context.Context) error) error {
	// FIXME: 1) Если в ctx уже есть транзакция, то используем её (значит ранее уже был вызван db.RunInTx),
	// FIXME: иначе создаём новую.

	// Проверяем, есть ли уже транзакция в контексте
	if tx := TxFromContext(ctx); tx != nil {
		// Транзакция уже есть, используем её
		return f(ctx)
	}

	// Создаем новую транзакцию
	tx, err := db.client.Tx(ctx)
	if err != nil {
		return fmt.Errorf("starting transaction: %w", err)
	}

	// Добавляем транзакцию в контекст
	txCtx := NewTxContext(ctx, tx)

	// Переменная для хранения результата функции f
	var funcErr error

	// FIXME: 3) Если в f случилась паника, то ролбечим транзакцию, панику при этом распространяем дальше.
	defer func() {
		if r := recover(); r != nil {
			// Произошла паника, откатываем транзакцию
			if rollbackErr := tx.Rollback(); rollbackErr != nil {
				// FIXME: 6) Ошибку роллбека необходимо тоже обработать
				// Логируем ошибку роллбека, но не затираем панику
				fmt.Printf("failed to rollback transaction after panic: %v\n", rollbackErr)
			}
			// Перебрасываем панику дальше
			panic(r)
		}

		// FIXME: 2) Если f завершилась ошибкой, то ролбечим транзакцию, а ошибку возвращаем наверх.
		if funcErr != nil {
			if rollbackErr := tx.Rollback(); rollbackErr != nil {
				// FIXME: 6) Ошибку роллбека необходимо тоже обработать
				// Возвращаем комбинированную ошибку
				funcErr = fmt.Errorf("transaction failed: %w, rollback failed: %v", funcErr, rollbackErr)
			}
			return
		}

		// FIXME: 4) Если f успешно завершилась, то коммитим транзакцию.
		// FIXME: 5) Ошибку коммита возвращаем наверх.
		if commitErr := tx.Commit(); commitErr != nil {
			funcErr = fmt.Errorf("committing transaction: %w", commitErr)
		}
	}()

	// Выполняем функцию в контексте транзакции
	funcErr = f(txCtx)

	return funcErr
}

func (db *Database) loadClient(ctx context.Context) *Client {
	tx := TxFromContext(ctx)
	if tx != nil {
		return tx.Client()
	}
	return db.client
}

// Exec executes a query that doesn't return rows. For example, in SQL, INSERT or UPDATE.
func (db *Database) Exec(ctx context.Context, query string, args ...any) (*sql.Result, error) {
	var res sql.Result
	err := db.loadClient(ctx).driver.Exec(ctx, query, args, &res)
	if err != nil {
		return nil, err
	}
	return &res, nil
}

// Query executes a query that returns rows, typically a SELECT in SQL.
func (db *Database) Query(ctx context.Context, query string, args ...any) (*sql.Rows, error) {
	var rows sql.Rows
	err := db.loadClient(ctx).driver.Query(ctx, query, args, &rows)
	if err != nil {
		return nil, err
	}
	return &rows, nil
}

// Chat is the client for interacting with the Chat builders.
func (db *Database) Chat(ctx context.Context) *ChatClient {
	return db.loadClient(ctx).Chat
}

// Message is the client for interacting with the Message builders.
func (db *Database) Message(ctx context.Context) *MessageClient {
	return db.loadClient(ctx).Message
}

// Problem is the client for interacting with the Problem builders.
func (db *Database) Problem(ctx context.Context) *ProblemClient {
	return db.loadClient(ctx).Problem
}
