[global]
env = "dev"

[log]
level = "info"

[servers]
[servers.debug]
addr = ":8079"
[servers.client]
addr = ":8080"
allow_origins = ["http://localhost:3000"]

[stores]
[stores.psql]
addr = "127.0.0.1:5432"
username = "chat-service"
password = "chat-service"
database = "chat-service"
debug = true

[clients]
[clients.keycloak]
base_path = "http://localhost:3010"
realm = "Bank"
client_id = "chat-service"
client_secret = "your-client-secret"
debug_mode = false
